"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from openrouter import components, utils
from openrouter._hooks import SDKHooks
from openrouter.types import OptionalNullable, UNSET
import sys
from typing import Any, Callable, Dict, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from openrouter.analytics import Analytics
    from openrouter.api_keys import APIKeys
    from openrouter.beta import Beta
    from openrouter.call_model import BaseTool, ResponseWrapper
    from openrouter.chat import Chat
    from openrouter.completions import Completions
    from openrouter.credits import Credits
    from openrouter.embeddings import Embeddings
    from openrouter.endpoints import Endpoints
    from openrouter.generations import Generations
    from openrouter.models_ import Models
    from openrouter.oauth import OAuth
    from openrouter.parameters import Parameters
    from openrouter.providers import Providers


class OpenRouter(BaseSDK):
    r"""OpenRouter API: OpenAI-compatible Chat Completions and Completions API with additional OpenRouter features
    https://openrouter.ai/docs - OpenRouter Documentation
    """

    beta: "Beta"
    analytics: "Analytics"
    r"""Analytics and usage endpoints"""
    credits: "Credits"
    r"""Credit management endpoints"""
    embeddings: "Embeddings"
    r"""Text embedding endpoints"""
    generations: "Generations"
    r"""Generation history endpoints"""
    models: "Models"
    r"""Model information endpoints"""
    endpoints: "Endpoints"
    r"""Endpoint information"""
    parameters: "Parameters"
    r"""Parameters endpoints"""
    providers: "Providers"
    r"""Provider information endpoints"""
    api_keys: "APIKeys"
    r"""API key management endpoints"""
    o_auth: "OAuth"
    r"""OAuth authentication endpoints"""
    chat: "Chat"
    completions: "Completions"
    _sub_sdk_map = {
        "beta": ("openrouter.beta", "Beta"),
        "analytics": ("openrouter.analytics", "Analytics"),
        "credits": ("openrouter.credits", "Credits"),
        "embeddings": ("openrouter.embeddings", "Embeddings"),
        "generations": ("openrouter.generations", "Generations"),
        "models": ("openrouter.models_", "Models"),
        "endpoints": ("openrouter.endpoints", "Endpoints"),
        "parameters": ("openrouter.parameters", "Parameters"),
        "providers": ("openrouter.providers", "Providers"),
        "api_keys": ("openrouter.api_keys", "APIKeys"),
        "o_auth": ("openrouter.oauth", "OAuth"),
        "chat": ("openrouter.chat", "Chat"),
        "completions": ("openrouter.completions", "Completions"),
    }

    def __init__(
        self,
        api_key: Optional[Union[Optional[str], Callable[[], Optional[str]]]] = None,
        server: Optional[str] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param api_key: The api_key required for authentication
        :param server: The server by name to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(type(client), HttpClient), (
            "The provided client must implement the HttpClient protocol."
        )

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(type(async_client), AsyncHttpClient), (
            "The provided async_client must implement the AsyncHttpClient protocol."
        )

        security: Any = None
        if callable(api_key):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: components.Security(api_key=api_key())
        else:
            security = components.Security(api_key=api_key)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server=server,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    async def call_model(
        self,
        request: Dict[str, Any],
        *,
        tools: Optional[list["BaseTool[Any, Any]"]] = None,
        max_tool_rounds: Optional[Union[int, Callable[[Any], bool]]] = None,
        options: Optional[Any] = None,
    ) -> "ResponseWrapper":
        """Create a response with multiple consumption patterns.

        This is the high-level API for calling OpenRouter models with automatic
        tool orchestration and flexible response consumption patterns.

        The method:
        - Makes exactly one API call to the OpenResponses endpoint
        - Supports automatic tool execution with validation
        - Returns a ResponseWrapper for multiple consumption methods
        - Handles streaming and non-streaming responses uniformly

        Args:
            request: Request parameters (same as beta.responses.send).
                     Must include "model" and "input" or other required fields.
                     Example: {"model": "openai/gpt-4", "input": "Hello!"}

            tools: Optional list of BaseTool instances for automatic execution.
                   Each tool must be a BaseTool subclass (RegularTool, GeneratorTool,
                   or ManualTool) with a Pydantic parameter model and execute method.
                   Default: None (no tools)

            max_tool_rounds: Maximum tool execution rounds.
                            Can be an int (default: 5, max: 10) or a callable that
                            takes ToolContext and returns bool.
                            Default: None (uses default of 5)

            options: Optional request options (timeout, headers, etc.).
                    Same as beta.responses.send options parameter.
                    Default: None

        Returns:
            ResponseWrapper: A wrapper providing multiple consumption methods:
                - await response.get_message() - Complete message with tool results
                - await response.get_text() - Text content only
                - async for delta in response.get_text_stream() - Stream text deltas
                - async for event in response.get_full_stream() - All SSE events
                - response.message - Cached message (None if not consumed)
                - response.text - Cached text (None if not consumed)
                - response.state - Current state (INITIALIZED, STREAMING, etc.)

        Raises:
            ValueError: If request is missing required fields
            ToolExecutionError: If tool execution fails
            ToolValidationError: If tool input validation fails
            MaxToolRoundsExceededError: If max_tool_rounds is exceeded
            StreamInterruptedError: If stream is interrupted
            Exception: Any other error from the API or tool execution

        Example:
            Simple text extraction:

            >>> from openrouter import OpenRouter
            >>>
            >>> async def main():
            ...     client = OpenRouter(api_key="...")
            ...     response = await client.call_model(
            ...         request={"model": "openai/gpt-4", "input": "Hello!"}
            ...     )
            ...     text = await response.get_text()
            ...     print(text)

            With automatic tool execution:

            >>> from openrouter import OpenRouter
            >>> from openrouter.call_model import RegularTool
            >>> from pydantic import BaseModel
            >>>
            >>> class WeatherParams(BaseModel):
            ...     location: str
            ...     unit: str = "celsius"
            >>>
            >>> class WeatherTool(RegularTool[WeatherParams, dict]):
            ...     name: str = "get_weather"
            ...     description: str = "Get current weather for a location"
            ...
            ...     async def execute(self, params: WeatherParams, context):
            ...         # Your weather API call here
            ...         return {"temp": 22, "unit": params.unit, "condition": "sunny"}
            >>>
            >>> async def main():
            ...     client = OpenRouter(api_key="...")
            ...     response = await client.call_model(
            ...         request={
            ...             "model": "openai/gpt-4",
            ...             "input": "What's the weather in San Francisco?"
            ...         },
            ...         tools=[WeatherTool()],
            ...         max_tool_rounds=3
            ...     )
            ...     # Tools are automatically executed!
            ...     message = await response.get_message()
            ...     print(message)

            Stream text deltas:

            >>> async def main():
            ...     client = OpenRouter(api_key="...")
            ...     response = await client.call_model(
            ...         request={"model": "openai/gpt-4", "input": "Write a story"}
            ...     )
            ...     async for delta in response.get_text_stream():
            ...         print(delta, end="", flush=True)

            Multiple consumption patterns:

            >>> async def main():
            ...     client = OpenRouter(api_key="...")
            ...     response = await client.call_model(
            ...         request={"model": "openai/gpt-4", "input": "Explain Python"}
            ...     )
            ...
            ...     # Get full message
            ...     message = await response.get_message()
            ...
            ...     # Get text only (from cached data - no additional API call)
            ...     text = await response.get_text()
            ...
            ...     # Check cached values
            ...     print(f"State: {response.state}")
            ...     print(f"Has message: {response.message is not None}")
            ...     print(f"Has text: {response.text is not None}")

        Note:
            - This method does NOT modify any existing SDK functionality
            - The old beta.responses.send() API continues to work unchanged
            - All existing response types and models continue to work
            - This is a new convenience method on top of existing infrastructure
        """
        # Import here to avoid circular dependencies
        from openrouter.call_model import call_model as call_model_func

        return await call_model_func(
            client=self,
            request=request,
            tools=tools,
            max_tool_rounds=max_tool_rounds,
            options=options,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
